// --- connReducer, useP2PHost ---
export const CONN_ACTYPE = {
  SETUP_PEER: "CONN_ACTYPE/SETUP_PEER",
  SETUP_CONN: "CONN_ACTYPE/SETUP_CONN",
  CLOSE_CONN: "CONN_ACTYPE/CLOSE_CONN",
  HOST_ROOM: "CONN_ACTYPE/HOST_ROOM",
  JOIN_ROOM: "CONN_ACTYPE/JOIN_ROOM",
  RAISE_ERROR: "CONN_ACTYPE/RAISE_ERROR",
  APPEND_LOG: "CONN_ACTYPE/APPEND_LOG",
  RESET_CONN_STATE: "CONN_ACTYPE/RESET_CONN_STATE",
};

export const CONN_STATUS = {
  OFFLINE: "CONN_STATE/OFFLINE",
  ONLINE: "CONN_STATE/ONLINE",
  HOST_WAITING: "CONN_STATE/HOST_WAITING",
  HOST_CONNECTED: "CONN_STATE/HOST_CONNECTED",
  GUEST_WAITING: "CONN_STATE/GUEST_WAITING",
  GUEST_CONNECTED: "CONN_STATE/GUEST_CONNECTED",
};

// --- gameReducer, useGameLogic ---
export const GAME_ACTYPE = {
  SYNC_STATE: "GAME_ACTYPE/SYNC_STATE",
  SETUP_GAME: "GAME_ACTYPE/SETUP_GAME",
  RESET_GAME: "GAME_ACTION/RESET_GAME",
  DRAW_CARDS: "GAME_ACTYPE/DRAW_CARDS",
  PLAY_CARDS: "GAME_ACTYPE/PLAY_CARDS",
  FLIP_CARDS: "GAME_ACTYPE/FLIP_CARDS",
  VOTE_WINNER: "GAME_ACTYPE/VOTE_WINNER",
  DECIDE_WINNER: "GAME_ACTYPE/DECIDE_WINNER",
  LOOT_CARDS: "GAME_ACTYPE/LOOT_CARDS",
  NEXT_ROUND: "GAME_ACTYPE/NEXT_ROUND",
};

export const GAME_PHASE = {
  GAME_READY: "GAME_PHASE/GAME_READY",
  GAME_OVER: "GAME_PHASE/GAME_OVER",
  DRAW_CARDS: "GAME_PHASE/DRAW_CARDS",
  PLAY_CARDS: "GAME_PHASE/PLAY_CARDS",
  FLIP_CARDS: "GAME_PHASE/FLIP_CARDS",
  VOTE_WINNER: "GAME_PHASE/VOTE_WINNER",
  DECIDE_WINNER: "GAME_PHASE/DECIDE_WINNER",
  LOOT_CARDS: "GAME_PHASE/LOOT_CARDS",
  NEXT_ROUND: "GAME_PHASE/NEXT_ROUND",
};

export const CARD_VALUES = [
  "A", "K", "Q", "J", "10", "9", "8", "7", "6", "5", "4", "3", "2",
];

export const CARD_SUITS = [
  "S", "D", "C", "H",
];