export const LOCAL_STORAGE_VARS = {
  GAME_STATE: "LOCAL_STORAGE/GAME_STATE",
  MY_ID: "LOCAL_STORAGE/MY_ID",
  HOST_ID: "LOCAL_STORAGE/HOST_ID",
};

export const CONNECTION_STATUS = {
  INIT: "CONNECTION/INIT",
  IDLE: "CONNECTION/IDLE",
  CONNECTED: "CONNECTION/CONNECTED",
};

export const CONNECTION_ACTION_TYPE = {
  HOST: "CONNECTION_ACTION/HOST",
  JOIN: "CONNECTION_ACTION/JOIN",
  DISCONNECT: "CONNECTION_ACTION/DISCONNECT",
};

export const GAME_ACTION_TYPE = {
  RESET: "GAME_ACTION/REST",
  SHUFFLE: "GAME_ACTION/SHUFFLE",

}

// --- gameReducer, useGameLogic ---
export const GAME_ACTYPE = {
  SYNC_STATE: "GAME_ACTYPE/SYNC_STATE",
  SETUP_GAME: "GAME_ACTYPE/SETUP_GAME",
  RESET_GAME: "GAME_ACTION/RESET_GAME",
  DRAW_CARDS: "GAME_ACTYPE/DRAW_CARDS",
  PLAY_CARDS: "GAME_ACTYPE/PLAY_CARDS",
  LOOT_CARDS: "GAME_ACTYPE/LOOT_CARDS",
  NEXT_ROUND: "GAME_ACTYPE/NEXT_ROUND",
};

export const GAME_PHASE = {
  GAME_START: "GAME_PHASE/GAME_START",
  GAME_OVER: "GAME_PHASE/GAME_OVER",
  ROUND_PREP: "GAME_PHASE/ROUND_PREP",
  ROUND_DRAWED: "GAME_PHASE/ROUND_DRAWED",
  ROUND_PLAYED: "GAME_PHASE/ROUND_PLAYED",
  ROUND_RESULT: "GAME_PHASE/ROUND_RESULT",
};

export const CARD_NUMBERS = [
  "A", "K", "Q", "J", "10", "9", "8", "7", "6", "5", "4", "3", "2",
];

export const CARD_SUITS = [
  "S", "D", "C", "H",
];